classdef inertialSymbol
    properties(Access = public)
        Radius      (1, 1)      double
        Position    (3, 1)      double
    end
    methods(Access = public)
        function draw(obj)
            x = obj.Position(1);
            y = obj.Position(2);
            z = obj.Position(3);
            res = 0.05;

            [theta, phi] = meshgrid(0:res:0.5*pi, 0.5*pi:res:1*pi);
            surf(x + obj.Radius * cos(theta) .* cos(phi), ...
                 y + obj.Radius * cos(theta) .* sin(phi), ...
                 z + obj.Radius * sin(theta), ...
                 "EdgeColor", "none", ...
                 "FaceColor", "k");
            [theta, phi] = meshgrid(-0.5*pi:res:0, 0.5*pi:res:1*pi);
            surf(x + obj.Radius * cos(theta) .* cos(phi), ...
                 y + obj.Radius * cos(theta) .* sin(phi), ...
                 z + obj.Radius * sin(theta), ...
                 "EdgeColor", "none", ...
                 "FaceColor", "w");
            [theta, phi] = meshgrid(0:res:0.5*pi, 0*pi:res:0.5*pi);
            surf(x + obj.Radius * cos(theta) .* cos(phi), ...
                 y + obj.Radius * cos(theta) .* sin(phi), ...
                 z + obj.Radius * sin(theta), ...
                 "EdgeColor", "none", ...
                 "FaceColor", "w");
            [theta, phi] = meshgrid(-0.5*pi:res:0, 0*pi:res:0.5*pi);
            surf(x + obj.Radius * cos(theta) .* cos(phi), ...
                 y + obj.Radius * cos(theta) .* sin(phi), ...
                 z + obj.Radius * sin(theta), ...
                 "EdgeColor", "none", ...
                 "FaceColor", "k");
            [theta, phi] = meshgrid(0:res:0.5*pi, pi:res:1.5*pi);
            surf(x + obj.Radius * cos(theta) .* cos(phi), ...
                 y + obj.Radius * cos(theta) .* sin(phi), ...
                 z + obj.Radius * sin(theta), ...
                 "EdgeColor", "none", ...
                 "FaceColor", "w");
            [theta, phi] = meshgrid(-0.5*pi:res:0, pi:res:1.5*pi);
            surf(x + obj.Radius * cos(theta) .* cos(phi), ...
                 y + obj.Radius * cos(theta) .* sin(phi), ...
                 z + obj.Radius * sin(theta), ...
                 "EdgeColor", "none", ...
                 "FaceColor", "k");
            [theta, phi] = meshgrid(0:res:0.5*pi, 1.5*pi:res:2*pi);
            surf(x + obj.Radius * cos(theta) .* cos(phi), ...
                 y + obj.Radius * cos(theta) .* sin(phi), ...
                 z + obj.Radius * sin(theta), ...
                 "EdgeColor", "none", ...
                 "FaceColor", "k");
            [theta, phi] = meshgrid(-0.5*pi:res:0, 1.5*pi:res:2*pi);
            surf(x + obj.Radius * cos(theta) .* cos(phi), ...
                 y + obj.Radius * cos(theta) .* sin(phi), ...
                 z + obj.Radius * sin(theta), ...
                 "EdgeColor", "none", ...
                 "FaceColor", "w");
        end
    end
end
